---
- block:
  - name: setup apt repository
    copy:
      src: sources.list
      dest: /etc/apt/sources.list
      owner: root
      group: root
      mode: "0644"
  - name: upgrade system
    apt: "upgrade=yes update_cache=yes autoremove=yes"
  - name: install system packages
    apt: "name={{ item }} state=latest"
    with_items:
      - sudo
      - chrony
  - name: purge unused packages
    apt: "name={{ item }} state=absent purge=yes"
    with_items:
      - rsync
  - name: create manager group
    group: "name={{ sysbase_manager_group }}"
  - name: create manager account
    user:
      name: "{{ sysbase_manager_account }}"
      group: "{{ sysbase_manager_group }}"
      shell: "/bin/bash"
      groups: "cdrom,floppy,audio,dip,video,plugdev,netdev"
  - name: set manager password
    shell: "echo '{{ sysbase_manager_account }}:{{ sysbase_manager_password }}' | chpasswd"
  - name: configure sudo accout list
    lineinfile: "dest=/etc/sudoers insertafter=^root line='{{ sysbase_manager_account }} ALL=(ALL:ALL) NOPASSWD: ALL'"
  - name: setup sudoers config
    lineinfile:
      dest: "/etc/sudoers"
      line: "#includedir /etc/sudoers.d"
      state: "present"
  - name: configure sudo to respect ssh agent forwarding variable
    copy:
      src: "allow-ssh-agent-forwarding"
      dest: "/etc/sudoers.d/allow-ssh-agent-forwarding"
      mode: "0440"
      owner: "root"
      group: "root"
  - name: setup chrony
    copy:
      src: "chrony.conf"
      dest: "/etc/chrony/chrony.conf"
      mode: "0644"
      owner: "root"
      group: "root"
  - name: setup timezone
    copy:
      src: "timezone"
      dest: "/etc/timezone"
      mode: "0644"
      owner: "root"
      group: "root"
  - name: setup localtime
    shell: "cp -f /usr/share/zoneinfo/Asia/Taipei /etc/localtime"
  - name: check if grub is used
    stat: path=/etc/default/grub
    register: grub_status
  - name: setup extra sysctl configuration
    copy:
      src: "99-custom.conf"
      dest: "/etc/sysctl.d/99-custom.conf"
      mode: "0644"
      owner: "root"
      group: "root"

  - block:
    - name: setup grub
      lineinfile:
        dest: "/etc/default/grub"
        regexp: "^GRUB_CMDLINE_LINUX="
        line: 'GRUB_CMDLINE_LINUX="elevator=noop"'
        state: "present"
    - name: update grub
      command: update-grub
    when: grub_status.stat.exists
  
  - block:
    - name: create swapfile
      command: dd if=/dev/zero of=/swapfile bs=1M count=2048
    - name: format swapfile
      command: mkswap /swapfile
    - name: setup swapfile permission
      file:
        path: /swapfile
        owner: root
        group: root
        mode: "0600"
    - name: activate swapfile
      command: swapon /swapfile
    - name: insert swap entry in fstab
      lineinfile:
        dest: /etc/fstab
        insertafter: EOF
        line: /swapfile swap swap defaults 0 0
    when: ansible_swaptotal_mb == 0
  
  tags:
    - sysbase
